# Generated by Django 3.0.14 on 2023-05-28 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20230523_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippinaddress',
            old_name='costomer',
            new_name='customer',
        ),
    ]
