# Generated by Django 3.0.14 on 2023-05-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20230528_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippinaddress',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
