# Generated by Django 3.0.14 on 2023-05-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20230528_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippinaddress',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='shippinaddress',
            name='state',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='shippinaddress',
            name='zipcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
